# Generated by Django 3.0.5 on 2020-04-26 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.TextField(blank=True)),
                ('parsed_response', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bookmarks.Bookmark')),
            ],
        ),
    ]
