# Generated by Django 3.0.5 on 2020-04-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='raw_response',
            new_name='response_body',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='response_headers',
            field=models.TextField(blank=True),
        ),
    ]
