# Generated by Django 3.0.5 on 2020-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20200425_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='parsed_response',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='response_body',
            new_name='headers_json',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='response_headers',
            new_name='opengraph_json',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='parsed_content',
            field=models.TextField(blank=True),
        ),
    ]
