# Generated by Django 3.0.5 on 2020-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_auto_20200425_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='favicon',
            field=models.URLField(blank=True),
        ),
    ]
