# Generated by Django 3.0.5 on 2020-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_auto_20200505_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
