# Generated by Django 3.0.5 on 2020-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0008_auto_20200505_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='favicon',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
